"use client"

import type { CartItem, Transaction } from "@/lib/types"
import { createClient } from "@/lib/supabase/client"
import { getQueueUserNote } from "@/lib/queue"

export interface TransactionTableRow {
  id?: string | number | null
  transaction_number?: string | null
  queue_number?: string | null
  customer_name?: string | null
  date?: string | null
  time?: string | null
  subtotal?: number | null
  discount_type?: string | null
  discount_percent?: number | null
  discount_amount?: number | null
  tax_amount?: number | null
  total?: number | null
  payment_method?: string | null
  cash_received?: number | null
  change_amount?: number | null
  processed_by?: string | null
  notes?: string | null
  order_status?: string | null
  voided?: boolean | null
  items?: CartItem[] | string | null
  created_at?: string | null
  updated_at?: string | null
  order_items?: OrderItemTableRow[] | null
}

export interface OrderItemTableRow {
  id?: string | number | null
  transaction_number?: string | null
  line_number?: number | null
  item_name?: string | null
  quantity?: number | null
  item_price?: number | null
  total_price?: number | null
  temperature?: string | null
  modifier_summary?: string | null
  notes?: string | null
  combo_name?: string | null
  metadata?: {
    addOns?: Array<{ id?: string; name: string; price?: number; selectedQuantity?: number }>
    productName?: string
    comboMealName?: string
    productCategory?: string
  } | null
}

export interface TransactionDetailItem {
  id: string
  lineNumber: number
  itemName: string
  quantity: number
  itemPrice: number
  totalPrice: number
  temperature?: string | null
  modifierSummary?: string | null
  addOns: Array<{ id: string; name: string; quantity: number; price: number }>
  notes?: string | null
  comboName?: string | null
}

export interface TransactionDetails {
  transactionId: string
  queueNumber: string | null
  customerName: string | null
  date: string
  time: string
  items: TransactionDetailItem[]
  subtotal: number
  discountAmount: number
  discountPercent: number
  discountType: "none" | "senior" | "pwd"
  taxAmount: number
  paymentMethod: "cash" | "gcash"
  totalAmount: number
  cashReceived: number
  changeAmount: number
  cashierName: string
  orderStatus: "pending" | "preparing" | "ready" | "completed" | "voided" | "cancelled"
  notes: string | null
  createdAt: string | null
  updatedAt: string | null
  voidedAt: string | null
  voidedBy: string | null
  source: "supabase-relational" | "supabase-json" | "local-fallback"
}

export const TRANSACTION_DETAILS_SCHEMA_SQL = `
alter table public.transactions
  add column if not exists queue_number text,
  add column if not exists customer_name text,
  add column if not exists tax_amount numeric not null default 0,
  add column if not exists notes text,
  add column if not exists order_status text not null default 'completed';

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  transaction_number text not null,
  line_number integer not null default 1,
  item_name text not null,
  quantity integer not null default 1,
  item_price numeric not null default 0,
  total_price numeric not null default 0,
  temperature text,
  modifier_summary text,
  notes text,
  combo_name text,
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_order_items_transaction_number
  on public.order_items (transaction_number, line_number);
`.trim()

function normalizeDiscountType(value: string | null | undefined): TransactionDetails["discountType"] {
  return value === "senior" || value === "pwd" ? value : "none"
}

function normalizeOrderStatus(value: string | null | undefined, isVoided: boolean | null | undefined): TransactionDetails["orderStatus"] {
  if (isVoided) return "voided"
  return value === "pending" || value === "preparing" || value === "ready" || value === "completed" || value === "voided" || value === "cancelled" ? value : "completed"
}

function normalizePaymentMethod(value: string | null | undefined): TransactionDetails["paymentMethod"] {
  return value === "gcash" ? "gcash" : "cash"
}

function getItemBasePrice(item: CartItem) {
  return item.comboMeal?.price ?? item.product.price
}

function formatModifierSummary(item: CartItem) {
  const segments: string[] = []
  if (item.temperature) {
    segments.push(item.temperature.charAt(0).toUpperCase() + item.temperature.slice(1))
  }
  if (item.addOns?.length) {
    segments.push(
      item.addOns
        .map((addOn) => `${addOn.name} x${addOn.selectedQuantity || 1}`)
        .join(", ")
    )
  }
  return segments.join(" • ") || null
}

function mapCartItemsToDetailItems(items: CartItem[]): TransactionDetailItem[] {
  return items.map((item, index) => {
    const itemPrice = getItemBasePrice(item)
    const addOns = (item.addOns || []).map((addOn) => ({
      id: addOn.id,
      name: addOn.name,
      quantity: addOn.selectedQuantity || 1,
      price: addOn.price,
    }))
    const addOnTotal = addOns.reduce((sum, addOn) => sum + addOn.price * addOn.quantity, 0)

    return {
      id: `${item.product.id}-${index}`,
      lineNumber: index + 1,
      itemName: item.product.name,
      quantity: item.quantity,
      itemPrice,
      totalPrice: (itemPrice + addOnTotal) * item.quantity,
      temperature: item.temperature || null,
      modifierSummary: formatModifierSummary(item),
      addOns,
      notes: item.notes || null,
      comboName: item.comboMeal?.name || null,
    }
  })
}

function mapOrderItemsToDetailItems(items: OrderItemTableRow[]): TransactionDetailItem[] {
  return items
    .slice()
    .sort((left, right) => (left.line_number || 0) - (right.line_number || 0))
    .map((item, index) => ({
      id: String(item.id ?? `${item.transaction_number || "tx"}-${index}`),
      lineNumber: item.line_number || index + 1,
      itemName: item.item_name || item.metadata?.productName || "Item",
      quantity: item.quantity || 1,
      itemPrice: Number(item.item_price || 0),
      totalPrice: Number(item.total_price || (item.item_price || 0) * (item.quantity || 1)),
      temperature: item.temperature || null,
      modifierSummary: item.modifier_summary || null,
      addOns: (item.metadata?.addOns || []).map((addOn, addOnIndex) => ({
        id: String(addOn.id ?? `${item.id ?? index}-addon-${addOnIndex}`),
        name: addOn.name,
        quantity: addOn.selectedQuantity || 1,
        price: Number(addOn.price || 0),
      })),
      notes: item.notes || null,
      comboName: item.combo_name || item.metadata?.comboMealName || null,
    }))
}

function parseItemsPayload(items: TransactionTableRow["items"]): CartItem[] {
  if (!items) return []
  if (typeof items === "string") {
    try {
      return JSON.parse(items) as CartItem[]
    } catch {
      return []
    }
  }
  return Array.isArray(items) ? items : []
}

function mapFallbackTransaction(transaction: Transaction): TransactionDetails {
  return {
    transactionId: transaction.id,
    queueNumber: transaction.queueNumber || null,
    customerName: transaction.customerName || null,
    date: transaction.date,
    time: transaction.time,
    items: mapCartItemsToDetailItems(transaction.items),
    subtotal: transaction.subtotal,
    discountAmount: transaction.discountAmount || 0,
    discountPercent: transaction.discountPercent || 0,
    discountType: transaction.discountType === "senior" || transaction.discountType === "pwd" ? transaction.discountType : "none",
    taxAmount: transaction.taxAmount || 0,
    paymentMethod: transaction.paymentMethod === "gcash" ? "gcash" : "cash",
    totalAmount: transaction.total,
    cashReceived: transaction.cashReceived,
    changeAmount: transaction.change || 0,
    cashierName: transaction.processedBy || "Unknown",
    orderStatus: normalizeOrderStatus(transaction.orderStatus, transaction.voided),
    notes: getQueueUserNote(transaction.notes) || null,
    createdAt: null,
    updatedAt: null,
    voidedAt: transaction.voidedAt || null,
    voidedBy: transaction.voidedBy || null,
    source: "local-fallback",
  }
}

function mapTransactionRow(row: TransactionTableRow, source: TransactionDetails["source"]): TransactionDetails {
  const rowItems = Array.isArray(row.order_items) && row.order_items.length > 0
    ? mapOrderItemsToDetailItems(row.order_items)
    : mapCartItemsToDetailItems(parseItemsPayload(row.items))

  return {
    transactionId: row.transaction_number || String(row.id || "Unknown"),
    queueNumber: row.queue_number || null,
    customerName: row.customer_name || null,
    date: row.date || "",
    time: row.time || "",
    items: rowItems,
    subtotal: Number(row.subtotal || 0),
    discountAmount: Number(row.discount_amount || 0),
    discountPercent: Number(row.discount_percent || 0),
    discountType: normalizeDiscountType(row.discount_type),
    taxAmount: Number(row.tax_amount || 0),
    paymentMethod: normalizePaymentMethod(row.payment_method),
    totalAmount: Number(row.total || 0),
    cashReceived: Number(row.cash_received || 0),
    changeAmount: Number(row.change_amount || 0),
    cashierName: row.processed_by || "Unknown",
    orderStatus: normalizeOrderStatus(row.order_status, row.voided),
    notes: getQueueUserNote(row.notes) || null,
    createdAt: row.created_at || null,
    updatedAt: row.updated_at || null,
    voidedAt: null,
    voidedBy: null,
    source,
  }
}

function isSchemaError(error: unknown) {
  const message =
    error && typeof error === "object" && "message" in error && typeof (error as { message?: unknown }).message === "string"
      ? (error as { message: string }).message.toLowerCase()
      : ""

  return (
    message.includes("could not find the") ||
    message.includes("does not exist") ||
    message.includes("relationship") ||
    message.includes("schema cache")
  )
}

export async function fetchTransactionDetails(transactionId: string, fallbackTransaction?: Transaction | null): Promise<TransactionDetails> {
  const supabase = createClient()

  try {
    const relationalResponse = await supabase
      .from("transactions")
      .select(
        "id, transaction_number, queue_number, customer_name, date, time, subtotal, discount_type, discount_percent, discount_amount, tax_amount, total, payment_method, cash_received, change_amount, processed_by, notes, order_status, voided, items, created_at, updated_at, order_items(id, transaction_number, line_number, item_name, quantity, item_price, total_price, temperature, modifier_summary, notes, combo_name, metadata)"
      )
      .eq("transaction_number", transactionId)
      .maybeSingle<TransactionTableRow>()

    if (!relationalResponse.error && relationalResponse.data) {
      return mapTransactionRow(relationalResponse.data, relationalResponse.data.order_items?.length ? "supabase-relational" : "supabase-json")
    }

    if (relationalResponse.error && !isSchemaError(relationalResponse.error)) {
      throw relationalResponse.error
    }

    const fallbackResponse = await supabase
      .from("transactions")
      .select("*")
      .eq("transaction_number", transactionId)
      .maybeSingle<TransactionTableRow>()

    if (fallbackResponse.error && !isSchemaError(fallbackResponse.error)) {
      throw fallbackResponse.error
    }

    if (fallbackResponse.data) {
      const orderItemsResponse = await supabase
        .from("order_items")
        .select("id, transaction_number, line_number, item_name, quantity, item_price, total_price, temperature, modifier_summary, notes, combo_name, metadata")
        .eq("transaction_number", transactionId)
        .order("line_number", { ascending: true })

      const row: TransactionTableRow = {
        ...fallbackResponse.data,
        order_items: orderItemsResponse.error ? null : (orderItemsResponse.data as OrderItemTableRow[]),
      }

      return mapTransactionRow(row, row.order_items?.length ? "supabase-relational" : "supabase-json")
    }
  } catch (error) {
    if (!fallbackTransaction) {
      throw error
    }
  }

  if (fallbackTransaction) {
    return mapFallbackTransaction(fallbackTransaction)
  }

  throw new Error("Transaction details are unavailable.")
}
