alter table public.transactions
  add column if not exists queue_number text,
  add column if not exists customer_name text,
  add column if not exists tax_amount numeric not null default 0,
  add column if not exists notes text,
  add column if not exists order_status text not null default 'completed';

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  transaction_number text not null,
  line_number integer not null default 1,
  item_name text not null,
  quantity integer not null default 1,
  item_price numeric not null default 0,
  total_price numeric not null default 0,
  temperature text,
  modifier_summary text,
  notes text,
  combo_name text,
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_order_items_transaction_number
  on public.order_items (transaction_number, line_number);
